server:
  port: 10086
spring:
  application:
    name: eureka-demo
eureka:
  instance:
    hostname: 10.61.181.14
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
   enable-self-preservation: false  #关闭自我保护
   eviction-interval-timer-in-ms: 5000 #每隔5秒进行一次服务列表清理