server:
  port: 1002
spring:
  datasource:
    url: jdbc:mysql://10.61.181.110:3306/tourismGis?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service
mybatis:
  type-aliases-package: com.lixin.userservice.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://10.61.181.14:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10